// import { Inter } from "next/font/google";
// import "../globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function DashboardLayout({ children }) {
    return (
      <>
        <h1>Admin login Navbar</h1>
  
        {children}
        <h1>Admin login Footer</h1>
      </>
    );
  }
  