import localfont from "next/font/local";
import "../../styles/globals.css";
import CommonHeader from "@/app/_GlobalComponents/CommonHeader";
import { Header } from "@/app/_GlobalComponents/Header";
import Footer from "@/app/_GlobalComponents/Footer";
import Contexts from "@/app/_GlobalComponents/Contexts";

const futureEarth = localfont({
  src: [
    {
      path: "../../../public/assets/fonts/future-earth/future-earth.ttf",
      weight: "900",
    },
  ],
  variable: "--font-futureEarth",
});

const futuraBKBT = localfont({
  src: [
    {
      path: "../../../public/assets/fonts/futura-bk-bt/FutuBk.ttf",
      weight: "900",
    },
  ],
  variable: "--font-futura",
});

export const metadata = {
  title: "Tech Dose",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${futureEarth.variable} ${futuraBKBT.variable} font-futura`}
    >
      <head></head>

      <body className="bg-[#201F1E]">
        <Contexts>
          {/* HEADER COMPONENT > LOGO+NAVBAR_C+SOCIAL_C */}
          <Header />
          {children}
          {/* FOOTER NAVBAR > NAVBAR_C */}
          <Footer />
        </Contexts>
      </body>
    </html>
  );
}
