import localfont from "next/font/local";
import "../../styles/globals.css";

const futureEarth = localfont({
  src: [
    {
      path: "../../../public/assets/fonts/future-earth/future-earth.ttf",
      weight: "900",
    },
  ],
  variable: "--font-futureEarth",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${futureEarth.variable}`}>
      <head></head>

      <body>
{/* HEADER COMPONENT > LOGO+NAVBAR_C+SOCIAL_C */}
{/* SECTION 1 > HEADING_C*/}
{/* SECTION 2 > HEADING_C*/}
{/* SECTION 3 > HEADING_C*/}
{/* SECTION 4 > HEADING_C*/}
{/* SECTION 5 > HEADING_C */}
{/* FOOTER NAVBAR > NAVBAR_C */}



        <span>Blog layout</span>
        {children}
      </body>
    </html>
  );
}
