import SideMenu from "@/app/_Components/_AdminDashboard/SideMenu";
import SideMenuResponsive from "@/app/_Components/_AdminDashboard/SideMenuResponsive";
import ProfileInfoHeader from "@/app/_Components/_AdminDashboard/ProfileInfoHeader";
import { futuraBKBT, futureEarth } from "../(blog)/layout";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${futureEarth.variable} ${futuraBKBT.variable} font-futura`}
    >
      <head></head>
      <body>
        <div className="admin-layout flex justify-center">
          <div className="flex gap-5 px-2 py-10 h-[100vh] w-[1200px] relative">
            <div>
              <SideMenu />
            </div>
            <div className="w-full flex flex-col gap-2 justify-between">
              <ProfileInfoHeader />
              {/* <SideMenuResponsive /> */}
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

// }
// {
//   /* Create layout design here with  Side Menu Component and profile Component and Main Content Component (children) inside it*/
// }
// {
//   /* Create Side Menu Component, render here  */
// }
