export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function DashboardLayout({ children }) {
    return (
      <>
        <h1>Admin Dashboard Navbar</h1>
  
        {children}
        <h1>Admin Dashboard Footer</h1>
      </>
    );
  }
  